<a href="https://colab.research.google.com/github/Tejaswimadastu/Deep_Learning/blob/main/LSTM_vs_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LSTM vs GRU for sentiment analysis

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,GRU,Dense
from sklearn.model_selection import train_test_split


In [2]:
texts = [
    "I love deep learning",
    "Artificial intelligence is amazing",
    "This course is excellent",
    "I am very happy today",
    "The movie was fantastic",
    "I hate this product",
    "This is very bad",
    "The service was terrible",
    "I am disappointed",
    "The experience was awful"
]

labels = [1,1,1,1,1,0,0,0,0,0]

In [7]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(texts)
sequences=tokenizer.texts_to_sequences(texts)
max_length=max([len(seq) for seq in sequences])
x=pad_sequences(sequences,maxlen=max_length)
y=np.array(labels)
print("X:", x)
print("Y:",y)

X: [[ 0  1  8  9 10]
 [ 0 11 12  2 13]
 [ 0  3 14  2 15]
 [ 1  6  7 16 17]
 [ 0  4 18  5 19]
 [ 0  1 20  3 21]
 [ 0  3  2  7 22]
 [ 0  4 23  5 24]
 [ 0  0  1  6 25]
 [ 0  4 26  5 27]]
Y: [1 1 1 1 1 0 0 0 0 0]


In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# LSTM Model

In [9]:
lstm_model=Sequential([
    Embedding(
        input_dim=len(tokenizer.word_index)+1,
        output_dim=16,
        input_length=max_length
    ),
    LSTM(64),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
lstm_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
lstm_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
history_lstm=lstm_model.fit(
    x_train,y_train,
    epochs=20,
    validation_data=(x_test,y_test),
    verbose=1

)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.6788 - val_accuracy: 1.0000 - val_loss: 0.6870
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.6770 - val_accuracy: 1.0000 - val_loss: 0.6866
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.6751 - val_accuracy: 1.0000 - val_loss: 0.6862
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.6730 - val_accuracy: 1.0000 - val_loss: 0.6857
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 1.0000 - loss: 0.6707 - val_accuracy: 1.0000 - val_loss: 0.6853
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 1.0000 - loss: 0.6682 - val_accuracy: 1.0000 - val_loss: 0.6848
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 1.0000 - loss: 0.6655 - val_accuracy: 1.0000 - val_loss: 0.6843
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step - accuracy: 1.0000 - loss: 0.6625 - val_accuracy: 1.0000 - val_loss: 0

In [22]:
lstm_loss,lstm_acc=lstm_model.evaluate(x_test,y_test,verbose=0)
print("LSTM Loss:",lstm_loss)
print("LSTM Accuracy:",lstm_acc)

LSTM Loss: 0.676158607006073
LSTM Accuracy: 1.0


GRU Model

In [21]:
gru_model=Sequential([
    Embedding(
        input_dim=len(tokenizer.word_index)+1,
        output_dim=16,
        input_length=max_length
    ),
    GRU(32),
    Dense(1,activation='sigmoid')
])

In [23]:
gru_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

gru_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
history_gru = gru_model.fit(
    x_train,
    y_train,
    epochs=20,
    validation_data=(x_test, y_test),
    verbose=1
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.6250 - loss: 0.6922 - val_accuracy: 0.5000 - val_loss: 0.6964
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.6910 - val_accuracy: 0.5000 - val_loss: 0.6965
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.6899 - val_accuracy: 0.5000 - val_loss: 0.6966
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.6887 - val_accuracy: 0.5000 - val_loss: 0.6967
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.6875 - val_accuracy: 0.5000 - val_loss: 0.6968
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.6863 - val_accuracy: 0.5000 - val_loss: 0.6969
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.6851 - val_accuracy: 0.5000 - val_loss: 0.6970
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.6837 - val_accuracy: 0.5000 - val_loss: 0.6971
E

In [25]:
print("LSTM Accuracy:", max(history_lstm.history['val_accuracy']))
print("GRU Accuracy:", max(history_gru.history['val_accuracy']))

LSTM Accuracy: 1.0
GRU Accuracy: 0.5


In [31]:
def predict_sentiment(model,text):
  seq=tokenizer.texts_to_sequences([text])
  padded=pad_sequences(seq,maxlen=max_length)
  prediction=model.predict(padded,verbose=0)[0][0]
  if prediction>=0.5:
    sentiment = "Positive"
  else:
    sentiment = "Negative"
  return sentiment, prediction

In [33]:
text = "I love Artificial Intelligent"

result_lstm, score_lstm = predict_sentiment(
    lstm_model,
    text
)

result_gru, score_gru = predict_sentiment(
    gru_model,
    text
)

print("LSTM Prediction")
print("Sentiment:", result_lstm)
print("Score:", score_lstm)

print("\nGRU Prediction")
print("Sentiment:", result_gru)
print("Score:", score_gru)

LSTM Prediction
Sentiment: Positive
Score: 0.5070875

GRU Prediction
Sentiment: Positive
Score: 0.5031949
